DATA:
  type: MNIST
MODEL:
  hidden_dims: []
  latent_dim: 16
  layer_type: LINEAR
  model_type: AE
TRAIN:
  batch_size: 256
  epochs: 10
  lr: 0.0001
  optim_type: ADAM
  random_seed: 2024
  weight_decay: 0.0001